config/routes.rb
Pitter::Application.routes.draw do

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users

  devise_scope :user do
    match 'users/sign_out', to: 'devise/sessions#destroy'
    match 'users/sign_in', to: 'devise/sessions#create'
    match 'users/:id', to: 'user#destroy', :via => :delete, :as => :admin_destroy_user
    match 'user/:id', to:'user#show', :via => :get, :as => :user
  end

  get 'users' => 'user#index', :as => :users
  get 'statistics' => 'user#statistics', :as => :statistics
  get 'user_posts' => 'posts#user_posts', :as => :user_posts

  root to: 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user, counter_cache: true
  belongs_to :post, counter_cache: true

  validates :text, presence: true

  attr_accessible :text
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user, counter_cache: true
  has_many :comments

  validates :text, :title, presence: true

  attr_accessible :text, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :comments
  has_many :posts

  devise :database_authenticatable, :registerable

  before_save { |user| user.login = login.downcase }

  validates :login,
            presence: true,
            uniqueness: { case_sensitive: false }

  validates_presence_of :password, on: :create
  validates :password,
            length: 8..50,
            # format: { message: 'should contains minimum one upercase letter and one digit', with: /^(?=.*[A-Z])(?!.*[^a-zA-Z0-9]).+$/ },
            format: { message: " wants you to complete this quest: /^(?=.*[A-Z])(?!.*[^a-zA-Z0-9]).+$/", with: /^(?=.*[A-Z])(?!.*[^a-zA-Z0-9]).+$/ },
            confirmation: true,
            if: :password_exists?

  def password_exists?
    password.present?
  end

  attr_accessible :login, :first_name, :last_name, :password, :password_confirmation, :admin

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def is_allow? options = {}, user_id
    (return true if current_user.admin) if :for_admin
    (return true if current_user.id == user_id || current_user.admin) if :for_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update, :destroy, :create]

  respond_to :html, :json

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user_id = current_user.id
    @comment.save

    redirect_to @post
  end

  def destroy
      @post = Post.find(params[:post_id])
      @comment = Comment.find(params[:id])
    if is_allow? :for_user, @comment.user_id
      @comment.destroy
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  respond_to :html

  def index
    @posts =  Post.order('comments_count DESC').limit(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]

  respond_to :html, :json

  def index
    @posts = Post.order('updated_at DESC')
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    @post.save
    respond_with(@post)
  end

  def update
    @post.update_attributes(params[:post])
    respond_with(@post)
  end

  def destroy
    if is_allow? :for_admin
      @post.destroy
      respond_with(@post)
    end
  end

  def user_posts
    @posts = Post.order('created_at DESC').select { |user_posts| user_posts.user_id == current_user.id }
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :check_visibility, only: [:index, :destroy]
  before_filter :authenticate_user!, only: [:statistics]

  respond_to :html

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: "User deleted."
  end

  def statistics
    @users = User.order('comments_count DESC', 'posts_count DESC')
  end

  private
    def check_visibility
      redirect_to root_path unless current_user && current_user.admin
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/comments/destroy.js.haml
$("#comment").html("#{escape_javascript(render 'posts/comments')}");

app/views/home/index.html.haml
%h1 Most popular posts
%table
  %tr
    %th Title
    %th Posted by
  - @posts.each do |post|
    %tr
      %td= link_to post.title, post
      %td= "#{post.user.first_name} #{post.user.last_name}" if post.user
%br
= link_to 'All Posts', posts_path
|
= link_to 'New Post', new_post_path
|
= link_to 'Statistics', statistics_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to 'TwitterPitter', '/', id: 'logo'
      %nav
        %ul.nav.pull-right.navbar-nav
          - if user_signed_in?
            %li= link_to 'Users', users_path if current_user.admin
            %li= link_to 'Your Posts', user_posts_path
            %li= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_registration_path
            %li= link_to 'Sign out', users_sign_out_path
          - else
            %li= link_to 'Sign in', users_sign_in_path
            %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Twitter-Pitter
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  %body
    %p.notice= notice
    %p.alert= alert
    = render 'layouts/header'
    .container
      = yield

app/views/posts/_comments.html.haml
%h2 Comments
- @post.comments.each do |comment|
  %p
    = comment.text
    - if current_user && (current_user == comment.user || current_user.admin)
      = link_to 'Delete', post_comment_path(@post.id, comment.id), method: :delete, confirm: 'Are you sure?', remote: true, disable_with: 'Deleting...'
  %i
    = "By #{comment.user.first_name} #{comment.user.last_name}" if comment.user
    = "#{time_ago_in_words comment.created_at} ago"
= form_for [@post, @post.comments.build] do |f|
  %p= f.text_area :text, size: '40x5'
  %p= f.submit 'Comment'

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .wysiwyg
    = f.label :text
    %br/
    = f.text_area :text, size: '40x5'
  / :javascript
  /   $('.wysiwyg').wysihtml5({toolbar: { color: true } });
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', @post

app/views/posts/index.html.haml
%h1 Listing posts
%table
  %tr
    %th Title
    %th User
    %th
    %th
    %th
  - @posts.each do |post|
    %tr
      %td= link_to post.title, post
      %td= "#{post.user.first_name} #{post.user.last_name}" if post.user
      - if current_user && current_user.admin
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Post', new_post_path
|
= link_to 'Back', root_path

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', :back

app/views/posts/show.html.haml
%p#notice= notice
%p
  %b Title:
  = @post.title
%p
  %b Text:
  = @post.text
%p
  %b Posted by:
  = "#{@post.user.first_name} #{@post.user.last_name}" if @post.user
  .comment
    = render 'comments'
= link_to 'Edit', edit_post_path(@post)
|
= link_to 'Back', posts_path

app/views/posts/user_posts.html.haml
%h1 My posts
%table
  %tr
    %th Title
    %th Date
  - @posts.each do |post|
    %tr
      %td= link_to post.title, post
      %td= post.created_at.to_formatted_s
%br
= link_to 'Back', :back

app/views/user/index.html.haml
%h1 Users
%table
  %tr
    %th User
    %th
  - @users.each do |user|
    %tr
      %td= link_to "#{user.first_name} #{user.last_name}", user_path(user)
      %td= link_to "Destroy", admin_destroy_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } if user != current_user
%br
= link_to 'Back', root_path

app/views/user/show.html.haml
%p#notice= notice
%p
  %b Login:
  = @user.login
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name
%p
  %b Admin:
  = @user.admin
= link_to 'Back', :back

app/views/user/statistics.html.haml
%h1 Statistics
%table
  %tr
    %th User
    %th Posts
    %th Comments
  - @users.each do |user|
    %tr
      %td= "#{user.first_name} #{user.last_name}"
      %td= user.posts_count
      %td= user.comments_count
%br
= link_to 'Back', root_path